### ISSUE TITLE
Status of the project

### ISSUE THREAD

**Issue by gigincg** [viebel/MetaTagsReRe#4]
Hey,
 I'm trying to use this package in a reason-react project of mine. Since I couldn't find an npm package for the project, I'm running the src files in my project. I tried to use the release version, but it isn't compiling. Even though the current versions seems to be compiling, There seems to be a few warnings.
This warning is thrown for a couple of external bindings. I'm new to Reason so I wanted to know if these can be avoided. 
"the external name is inferred from val name is unsafe from refactoring when changing value"

**Comment by maarekj** [comment]
This project is no longer being maintained.
On my others projects I migrated on **react-helmet**.
I you want the binding for react-helmet, I can share the mine with a gist.

Thanks you for your pull request.

**Comment by gigincg** [comment]
@maarekj Would be awesome if you could share a gist for react-helmet.

**Comment by maarekj** [comment]
https://gist.github.com/maarekj/96015e983588590707390402d0db3111
